[env]
TERM = "xterm-256color"

[window]
decorations = "None"
decorations_theme_variant = "Dark"
startup_mode = "Maximized"

[font]
normal.family = "Maple Mono SC NF"
size = 12
normal.style = "Regular"
