export PATH="$HOME/.local/bin:$HOME/.luarocks/bin:$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export npm_config_prefix="$HOME/.local"
export PYTHONPATH="$HOME/room_monitor/ctwing_nb_sdk"
export EDITOR="nvim"
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export KERL_BUILD_DOCS=yes
export RUSTUP_HOME="$HOME/.rustup"
export CARGO_HOME="$HOME/.cargo"
export KITTY_LISTEN_ON=unix:/tmp/mykitty
. "$HOME/.asdf/asdf.sh"
. "$HOME/.cargo/env"
